CREATE table emilia_romagna
(
    aggiornamento DATE NOT NULL UNIQUE PRIMARY KEY,
    url TEXT,

    positivi_tot_counter INTEGER,
    test_refertati_tot_counter INTEGER,
    isolamento_domiciliare_gauge INTEGER,
    terapia_intensiva_gauge INTEGER,
    decessi_tot_counter INTEGER,
    decessi_m_die_gauge INTEGER,
    decessi_f_die_gauge INTEGER,
    guariti_tot_counter INTEGER,
    clinicamente_guariti_tot_counter INTEGER,
    guariti_negativi_tot_counter INTEGER,
    decessi_die_pc_gauge INTEGER,
    decessi_die_pr_gauge INTEGER,
    decessi_die_re_gauge INTEGER,
    decessi_die_mo_gauge INTEGER,
    decessi_die_bo_gauge INTEGER,
    decessi_die_fe_gauge INTEGER,
    decessi_die_ra_gauge INTEGER,
    decessi_die_fc_gauge INTEGER,
    decessi_die_rn_gauge INTEGER,
    decessi_die_fuoriregione_gauge INTEGER,
    positivi_pc_gauge INTEGER,
    positivi_pr_gauge INTEGER,
    positivi_re_gauge INTEGER,
    positivi_mo_gauge INTEGER,
    positivi_bo_gauge INTEGER,
    positivi_fe_gauge INTEGER,
    positivi_ra_gauge INTEGER,
    positivi_fc_gauge INTEGER,
    positivi_rn_gauge INTEGER
);
